name: Build and deploy Jekyll blog site to GitHub Pages

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build Jekyll site
        uses: helaili/jekyll-action@2.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: "main" # The branch GitHub Pages serves
          jekyll_src: "./blog" # Path to your Jekyll site source

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./blog/_site # Adjust if your Jekyll output directory is different
